Repository verida/verida-js, pull requests merged in 2021-11, with the labels that each got.

#89 updating build process docs
  .nvmrc
  README.md
Labels: documentation, dependencies

#101 Issue/99 update schema urls
  packages/account-web-vault/src/interfaces.ts
  packages/client-ts/package.json
  packages/client-ts/src/context/context.ts
  packages/client-ts/src/context/datastore.ts
  packages/client-ts/src/context/db-registry.ts
  packages/client-ts/src/context/engines/verida/messaging/engine.ts
  packages/client-ts/src/context/engines/verida/messaging/inbox.ts
  packages/client-ts/src/context/engines/verida/messaging/outbox.ts
  packages/client-ts/src/context/profiles/profile.ts
  packages/client-ts/src/context/schema.ts
  packages/client-ts/test/config.ts
  packages/client-ts/test/profile.tests.ts
  packages/client-ts/test/schema.tests.ts
  packages/client-ts/test/verida/datastore.tests.ts
  packages/client-ts/test/verida/messaging.tests.ts
  yarn.lock
Labels: refactor, architecture

#102 feat: configured better docs with jsdocs
  packages/client-ts/README.api.md
  packages/client-ts/jsdoc.json
  packages/client-ts/package.json
  packages/client-ts/src/client.ts
  packages/client-ts/src/context/context.ts
  packages/client-ts/src/context/datastore.ts
  packages/client-ts/src/context/db-registry.ts
  packages/client-ts/src/context/engines/base.ts
  packages/client-ts/src/context/engines/verida/database/base-db.ts
  packages/client-ts/src/context/engines/verida/database/client.ts
  packages/client-ts/src/context/engines/verida/database/db-encrypted.ts
  packages/client-ts/src/context/engines/verida/database/db-public.ts
  packages/client-ts/src/context/engines/verida/database/engine.ts
  packages/client-ts/src/context/engines/verida/database/interfaces.ts
  packages/client-ts/src/context/engines/verida/database/utils.ts
  packages/client-ts/src/context/engines/verida/messaging/engine.ts
  packages/client-ts/src/context/engines/verida/messaging/inbox.ts
  packages/client-ts/src/context/engines/verida/messaging/outbox.ts
  packages/client-ts/src/context/interfaces.ts
  packages/client-ts/src/context/messaging.ts
  packages/client-ts/src/context/profiles/profile.ts
  packages/client-ts/src/context/schema.ts
  packages/client-ts/src/did-context-manager.ts
  packages/client-ts/src/interfaces.ts
  packages/client-ts/src/network.ts
Labels: bug, documentation
